// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: gotocompany/shield/v1beta1/shield.proto

package shieldv1beta1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on ListUserResourcesRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListUserResourcesRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListUserResourcesRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListUserResourcesRequestMultiError, or nil if none found.
func (m *ListUserResourcesRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ListUserResourcesRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for UserId

	// no validation rules for Namespace

	// no validation rules for Type

	if len(errors) > 0 {
		return ListUserResourcesRequestMultiError(errors)
	}

	return nil
}

// ListUserResourcesRequestMultiError is an error wrapping multiple validation
// errors returned by ListUserResourcesRequest.ValidateAll() if the designated
// constraints aren't met.
type ListUserResourcesRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListUserResourcesRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListUserResourcesRequestMultiError) AllErrors() []error { return m }

// ListUserResourcesRequestValidationError is the validation error returned by
// ListUserResourcesRequest.Validate if the designated constraints aren't met.
type ListUserResourcesRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListUserResourcesRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListUserResourcesRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListUserResourcesRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListUserResourcesRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListUserResourcesRequestValidationError) ErrorName() string {
	return "ListUserResourcesRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ListUserResourcesRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListUserResourcesRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListUserResourcesRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListUserResourcesRequestValidationError{}

// Validate checks the field values on ListUserResourcesResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ListUserResourcesResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ListUserResourcesResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ListUserResourcesResponseMultiError, or nil if none found.
func (m *ListUserResourcesResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *ListUserResourcesResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetResources()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ListUserResourcesResponseValidationError{
					field:  "Resources",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ListUserResourcesResponseValidationError{
					field:  "Resources",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetResources()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ListUserResourcesResponseValidationError{
				field:  "Resources",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ListUserResourcesResponseMultiError(errors)
	}

	return nil
}

// ListUserResourcesResponseMultiError is an error wrapping multiple validation
// errors returned by ListUserResourcesResponse.ValidateAll() if the
// designated constraints aren't met.
type ListUserResourcesResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ListUserResourcesResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ListUserResourcesResponseMultiError) AllErrors() []error { return m }

// ListUserResourcesResponseValidationError is the validation error returned by
// ListUserResourcesResponse.Validate if the designated constraints aren't met.
type ListUserResourcesResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ListUserResourcesResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ListUserResourcesResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ListUserResourcesResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ListUserResourcesResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ListUserResourcesResponseValidationError) ErrorName() string {
	return "ListUserResourcesResponseValidationError"
}

// Error satisfies the builtin error interface
func (e ListUserResourcesResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sListUserResourcesResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ListUserResourcesResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ListUserResourcesResponseValidationError{}
